from __future__ import annotations

SKILL_CATALOG: list[dict[str, object]] = [
    {"name": "Python", "category": "Programming", "aliases": ["python3"]},
    {"name": "Java", "category": "Programming", "aliases": []},
    {"name": "JavaScript", "category": "Programming", "aliases": ["js"]},
    {"name": "TypeScript", "category": "Programming", "aliases": ["ts"]},
    {"name": "C", "category": "Programming", "aliases": []},
    {"name": "C++", "category": "Programming", "aliases": ["cpp"]},
    {"name": "C#", "category": "Programming", "aliases": ["csharp"]},
    {"name": "Go", "category": "Programming", "aliases": ["golang"]},
    {"name": "Rust", "category": "Programming", "aliases": []},
    {"name": "Kotlin", "category": "Programming", "aliases": []},
    {"name": "Swift", "category": "Programming", "aliases": []},
    {"name": "Ruby", "category": "Programming", "aliases": []},
    {"name": "PHP", "category": "Programming", "aliases": []},
    {"name": "Scala", "category": "Programming", "aliases": []},
    {"name": "R", "category": "Programming", "aliases": []},
    {"name": "MATLAB", "category": "Programming", "aliases": []},
    {"name": "Bash", "category": "Programming", "aliases": ["shell scripting"]},
    {"name": "PowerShell", "category": "Programming", "aliases": []},
    {"name": "SQL", "category": "Database", "aliases": []},
    {"name": "PL/SQL", "category": "Database", "aliases": []},
    {"name": "T-SQL", "category": "Database", "aliases": []},
    {"name": "React", "category": "Frontend", "aliases": ["reactjs"]},
    {"name": "Next.js", "category": "Frontend", "aliases": ["nextjs"]},
    {"name": "Vue.js", "category": "Frontend", "aliases": ["vue"]},
    {"name": "Nuxt.js", "category": "Frontend", "aliases": ["nuxt"]},
    {"name": "Angular", "category": "Frontend", "aliases": []},
    {"name": "Svelte", "category": "Frontend", "aliases": []},
    {"name": "HTML", "category": "Frontend", "aliases": ["html5"]},
    {"name": "CSS", "category": "Frontend", "aliases": ["css3"]},
    {"name": "Tailwind CSS", "category": "Frontend", "aliases": ["tailwind"]},
    {"name": "Bootstrap", "category": "Frontend", "aliases": []},
    {"name": "Material UI", "category": "Frontend", "aliases": ["mui"]},
    {"name": "Redux", "category": "Frontend", "aliases": []},
    {"name": "Zustand", "category": "Frontend", "aliases": []},
    {"name": "Vite", "category": "Frontend", "aliases": []},
    {"name": "Webpack", "category": "Frontend", "aliases": []},
    {"name": "FastAPI", "category": "Backend", "aliases": ["fast api"]},
    {"name": "Django", "category": "Backend", "aliases": []},
    {"name": "Flask", "category": "Backend", "aliases": []},
    {"name": "Spring Boot", "category": "Backend", "aliases": ["springboot"]},
    {"name": "Node.js", "category": "Backend", "aliases": ["node"]},
    {"name": "Express.js", "category": "Backend", "aliases": ["express"]},
    {"name": "NestJS", "category": "Backend", "aliases": ["nest"]},
    {"name": "ASP.NET Core", "category": "Backend", "aliases": ["dotnet core"]},
    {"name": "Laravel", "category": "Backend", "aliases": []},
    {"name": "Ruby on Rails", "category": "Backend", "aliases": ["rails"]},
    {"name": "GraphQL", "category": "Backend", "aliases": []},
    {"name": "REST APIs", "category": "Backend", "aliases": ["rest api"]},
    {"name": "gRPC", "category": "Backend", "aliases": []},
    {"name": "Microservices", "category": "Backend", "aliases": []},
    {"name": "PostgreSQL", "category": "Database", "aliases": ["postgres"]},
    {"name": "MySQL", "category": "Database", "aliases": []},
    {"name": "SQLite", "category": "Database", "aliases": []},
    {"name": "MongoDB", "category": "Database", "aliases": ["mongo"]},
    {"name": "Redis", "category": "Database", "aliases": []},
    {"name": "Elasticsearch", "category": "Database", "aliases": ["elastic search"]},
    {"name": "Cassandra", "category": "Database", "aliases": []},
    {"name": "DynamoDB", "category": "Database", "aliases": []},
    {"name": "Snowflake", "category": "Database", "aliases": []},
    {"name": "BigQuery", "category": "Database", "aliases": []},
    {"name": "Databricks", "category": "Data", "aliases": []},
    {"name": "Apache Spark", "category": "Data", "aliases": ["spark"]},
    {"name": "Hadoop", "category": "Data", "aliases": []},
    {"name": "dbt", "category": "Data", "aliases": []},
    {"name": "Airflow", "category": "Data", "aliases": ["apache airflow"]},
    {"name": "Kafka", "category": "Data", "aliases": ["apache kafka"]},
    {"name": "Pandas", "category": "Data", "aliases": []},
    {"name": "NumPy", "category": "Data", "aliases": []},
    {"name": "SciPy", "category": "Data", "aliases": []},
    {"name": "Jupyter", "category": "Data", "aliases": ["jupyter notebook"]},
    {"name": "Tableau", "category": "Analytics", "aliases": []},
    {"name": "Power BI", "category": "Analytics", "aliases": ["powerbi"]},
    {"name": "Looker", "category": "Analytics", "aliases": []},
    {"name": "Google Analytics", "category": "Analytics", "aliases": ["ga4"]},
    {"name": "A/B Testing", "category": "Analytics", "aliases": ["ab testing"]},
    {"name": "Statistics", "category": "Analytics", "aliases": []},
    {"name": "Machine Learning", "category": "ML", "aliases": ["ml"]},
    {"name": "Deep Learning", "category": "ML", "aliases": ["dl"]},
    {"name": "PyTorch", "category": "ML", "aliases": ["torch"]},
    {"name": "TensorFlow", "category": "ML", "aliases": ["tf"]},
    {"name": "Keras", "category": "ML", "aliases": []},
    {"name": "Scikit-learn", "category": "ML", "aliases": ["sklearn"]},
    {"name": "XGBoost", "category": "ML", "aliases": []},
    {"name": "LightGBM", "category": "ML", "aliases": []},
    {"name": "NLP", "category": "ML", "aliases": ["natural language processing"]},
    {"name": "Computer Vision", "category": "ML", "aliases": []},
    {"name": "LLM Fine-tuning", "category": "ML", "aliases": ["llm tuning"]},
    {"name": "Prompt Engineering", "category": "ML", "aliases": []},
    {"name": "MLflow", "category": "MLOps", "aliases": []},
    {"name": "DVC", "category": "MLOps", "aliases": []},
    {"name": "Kubeflow", "category": "MLOps", "aliases": []},
    {"name": "MLOps", "category": "MLOps", "aliases": ["ml ops"]},
    {"name": "Feature Engineering", "category": "ML", "aliases": []},
    {"name": "Docker", "category": "DevOps", "aliases": []},
    {"name": "Kubernetes", "category": "DevOps", "aliases": ["k8s"]},
    {"name": "Terraform", "category": "DevOps", "aliases": []},
    {"name": "Ansible", "category": "DevOps", "aliases": []},
    {"name": "Jenkins", "category": "DevOps", "aliases": []},
    {"name": "GitHub Actions", "category": "DevOps", "aliases": ["github action"]},
    {"name": "GitLab CI", "category": "DevOps", "aliases": ["gitlab ci/cd"]},
    {"name": "CircleCI", "category": "DevOps", "aliases": []},
    {"name": "CI/CD", "category": "DevOps", "aliases": ["continuous integration"]},
    {"name": "Linux", "category": "DevOps", "aliases": []},
    {"name": "Nginx", "category": "DevOps", "aliases": []},
    {"name": "Apache", "category": "DevOps", "aliases": []},
    {"name": "Prometheus", "category": "DevOps", "aliases": []},
    {"name": "Grafana", "category": "DevOps", "aliases": []},
    {"name": "AWS", "category": "Cloud", "aliases": ["amazon web services"]},
    {"name": "Amazon EC2", "category": "Cloud", "aliases": ["ec2"]},
    {"name": "Amazon S3", "category": "Cloud", "aliases": ["s3"]},
    {"name": "AWS Lambda", "category": "Cloud", "aliases": ["lambda"]},
    {"name": "Amazon RDS", "category": "Cloud", "aliases": ["rds"]},
    {"name": "Azure", "category": "Cloud", "aliases": ["microsoft azure"]},
    {"name": "Azure Functions", "category": "Cloud", "aliases": []},
    {"name": "Azure DevOps", "category": "Cloud", "aliases": []},
    {"name": "GCP", "category": "Cloud", "aliases": ["google cloud"]},
    {"name": "Cloud Run", "category": "Cloud", "aliases": []},
    {"name": "Firebase", "category": "Cloud", "aliases": []},
    {"name": "CloudFormation", "category": "Cloud", "aliases": []},
    {"name": "Computer Networks", "category": "Infrastructure", "aliases": ["networking"]},
    {"name": "TCP/IP", "category": "Infrastructure", "aliases": []},
    {"name": "DNS", "category": "Infrastructure", "aliases": []},
    {"name": "Load Balancing", "category": "Infrastructure", "aliases": []},
    {"name": "System Design", "category": "Architecture", "aliases": []},
    {"name": "Distributed Systems", "category": "Architecture", "aliases": []},
    {"name": "Event-Driven Architecture", "category": "Architecture", "aliases": []},
    {"name": "ETL", "category": "Data", "aliases": []},
    {"name": "Data Warehousing", "category": "Data", "aliases": []},
    {"name": "Data Modeling", "category": "Data", "aliases": []},
    {"name": "Data Governance", "category": "Data", "aliases": []},
    {"name": "Data Visualization", "category": "Analytics", "aliases": []},
    {"name": "Business Intelligence", "category": "Analytics", "aliases": ["bi"]},
    {"name": "Figma", "category": "Design", "aliases": []},
    {"name": "Adobe XD", "category": "Design", "aliases": []},
    {"name": "Sketch", "category": "Design", "aliases": []},
    {"name": "User Research", "category": "Design", "aliases": []},
    {"name": "Wireframing", "category": "Design", "aliases": []},
    {"name": "Prototyping", "category": "Design", "aliases": []},
    {"name": "Design Systems", "category": "Design", "aliases": []},
    {"name": "Accessibility", "category": "Design", "aliases": ["a11y"]},
    {"name": "UX Design", "category": "Design", "aliases": []},
    {"name": "UI Design", "category": "Design", "aliases": []},
    {"name": "Agile", "category": "Product", "aliases": []},
    {"name": "Scrum", "category": "Product", "aliases": []},
    {"name": "Kanban", "category": "Product", "aliases": []},
    {"name": "Product Management", "category": "Product", "aliases": []},
    {"name": "Roadmapping", "category": "Product", "aliases": []},
    {"name": "Stakeholder Management", "category": "Product", "aliases": []},
    {"name": "Requirements Gathering", "category": "Product", "aliases": []},
    {"name": "Jira", "category": "Product", "aliases": []},
    {"name": "Confluence", "category": "Product", "aliases": []},
    {"name": "Salesforce", "category": "Business Systems", "aliases": []},
    {"name": "HubSpot", "category": "Business Systems", "aliases": []},
    {"name": "SAP", "category": "Business Systems", "aliases": []},
    {"name": "Oracle ERP", "category": "Business Systems", "aliases": []},
    {"name": "ServiceNow", "category": "Business Systems", "aliases": []},
    {"name": "Cybersecurity", "category": "Security", "aliases": []},
    {"name": "Application Security", "category": "Security", "aliases": ["appsec"]},
    {"name": "Penetration Testing", "category": "Security", "aliases": ["pentesting"]},
    {"name": "Threat Modeling", "category": "Security", "aliases": []},
    {"name": "IAM", "category": "Security", "aliases": ["identity and access management"]},
    {"name": "OAuth", "category": "Security", "aliases": []},
    {"name": "OpenID Connect", "category": "Security", "aliases": ["oidc"]},
    {"name": "SAML", "category": "Security", "aliases": []},
    {"name": "Encryption", "category": "Security", "aliases": []},
    {"name": "SOC 2", "category": "Security", "aliases": []},
    {"name": "HIPAA", "category": "Compliance", "aliases": []},
    {"name": "GDPR", "category": "Compliance", "aliases": []},
    {"name": "Quality Assurance", "category": "QA", "aliases": ["qa"]},
    {"name": "Test Automation", "category": "QA", "aliases": []},
    {"name": "Selenium", "category": "QA", "aliases": []},
    {"name": "Cypress", "category": "QA", "aliases": []},
    {"name": "Playwright", "category": "QA", "aliases": []},
    {"name": "Pytest", "category": "QA", "aliases": []},
    {"name": "Jest", "category": "QA", "aliases": []},
    {"name": "Vitest", "category": "QA", "aliases": []},
    {"name": "Unit Testing", "category": "QA", "aliases": []},
    {"name": "Integration Testing", "category": "QA", "aliases": []},
    {"name": "End-to-End Testing", "category": "QA", "aliases": ["e2e testing"]},
    {"name": "Manual Testing", "category": "QA", "aliases": []},
    {"name": "API Testing", "category": "QA", "aliases": []},
    {"name": "Project Management", "category": "Operations", "aliases": []},
    {"name": "Process Improvement", "category": "Operations", "aliases": []},
    {"name": "Documentation", "category": "Operations", "aliases": []},
    {"name": "Technical Writing", "category": "Operations", "aliases": []},
    {"name": "Customer Support", "category": "Operations", "aliases": []},
    {"name": "Troubleshooting", "category": "Operations", "aliases": []},
    {"name": "Excel", "category": "Business Tools", "aliases": ["microsoft excel"]},
    {"name": "Word", "category": "Business Tools", "aliases": ["microsoft word"]},
    {"name": "PowerPoint", "category": "Business Tools", "aliases": ["microsoft powerpoint"]},
    {"name": "Communication", "category": "Professional", "aliases": []},
    {"name": "Leadership", "category": "Professional", "aliases": []},
    {"name": "Mentoring", "category": "Professional", "aliases": []},
    {"name": "Teamwork", "category": "Professional", "aliases": []},
    {"name": "Problem Solving", "category": "Professional", "aliases": []},
    {"name": "Critical Thinking", "category": "Professional", "aliases": []},
    {"name": "Time Management", "category": "Professional", "aliases": []},
    {"name": "Public Speaking", "category": "Professional", "aliases": []},
]
