from app.main import app


def test_openapi_includes_expected_route_surface():
    schema = app.openapi()
    paths = schema["paths"]
    expected = {
        "/health/",
        "/health/db_counts",
        "/auth/register",
        "/auth/login",
        "/auth/me",
        "/auth/logout",
        "/skills/",
        "/skills/{skill_id}",
        "/skills/extract/skills/{snapshot_id}",
        "/skills/gaps",
        "/skills/gaps/confirmed",
        "/skills/confirmations/",
        "/skills/confirmations/profile",
        "/jobs/",
        "/jobs/submit",
        "/jobs/{job_id}/moderate",
        "/jobs/{job_id}/roles",
        "/evidence/analyze",
        "/evidence/",
        "/evidence/{evidence_id}",
        "/ingest/resume/text",
        "/ingest/resume/pdf",
        "/ingest/resume/{snapshot_id}/promote",
        "/projects/",
        "/projects/{project_id}",
        "/projects/{project_id}/skills",
        "/dashboard/summary",
        "/admin/summary",
        "/admin/users",
        "/admin/users/{user_id}",
        "/admin/jobs",
        "/admin/jobs/{job_id}/moderation",
        "/roles/",
        "/roles/{role_id}/compute_weights",
        "/roles/{role_id}/weights",
        "/taxonomy/aliases/{skill_id}",
        "/taxonomy/relations",
        "/tailor/job/ingest",
        "/tailor/match",
        "/tailor/preview",
        "/tailor/resumes",
        "/tailor/resumes/{tailored_id}",
        "/tailor/history",
        "/tailor/history/{history_id}",
        "/tailor/history/compare",
        "/tailor/settings/status",
        "/tailor/{tailored_id}/rewrite",
        "/tailor/{tailored_id}/export/docx",
        "/tailor/{tailored_id}/export/pdf",
        "/portfolio/items",
    }
    for path in expected:
        assert path in paths
